In [2]:
import numpy as np 
import pandas as pd

columns = ['A1', 'A2','A3','A4','A5','A6','A7','A8','A9','A10','age','gender','ethnicity','jundice','austim','coun_of_res','used_app_before','result','age_desc','relation','Class/ASD']

df=pd.read_csv("C:/Users/Admin/Downloads/Autism-Adult-Data.csv",names=columns)

In [3]:
df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,gender,ethnicity,jundice,austim,coun_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,'United States',no,6,'18 and more',Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5,'18 and more',Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8,'18 and more',Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,'United States',no,6,'18 and more',Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,?,no,no,Egypt,no,2,'18 and more',?,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7,'18 and more',Self,YES
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3,'18 and more',Parent,NO
701,1,0,1,1,1,0,1,1,0,1,...,f,?,no,no,Russia,no,7,'18 and more',?,YES
702,1,0,0,1,1,0,1,0,1,1,...,m,'South Asian',no,no,Pakistan,no,6,'18 and more',Self,NO
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8,'18 and more',Self,YES

In [4]:
#age desc
#class/ASD
#age>>used_app_before




df.isnull().sum()

A1                 0
A2                 0
A3                 0
A4                 0
A5                 0
A6                 0
A7                 0
A8                 0
A9                 0
A10                0
age                0
gender             0
ethnicity          0
jundice            0
austim             0
coun_of_res        0
used_app_before    0
result             0
age_desc           0
relation           0
Class/ASD          0
dtype: int64

In [5]:
df.describe(include='all')

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,gender,ethnicity,jundice,austim,coun_of_res,used_app_before,result,age_desc,relation,Class/ASD
count,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,...,704,704,704,704,704,704,704.000000,704,704,704
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,12,2,2,67,2,NaN,1,6,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,m,White-European,no,no,'United States',no,NaN,'18 and more',Self,NO
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,367,233,635,613,113,692,NaN,704,522,515
mean,0.721591,0.453125,0.457386,0.495739,0.498580,0.284091,0.417614,0.649148,0.323864,0.573864,...,NaN,NaN,NaN,NaN,NaN,NaN,4.875000,NaN,NaN,NaN
std,0.448535,0.498152,0.498535,0.500337,0.500353,0.451301,0.493516,0.477576,0.468281,0.494866,...,NaN,NaN,NaN,NaN,NaN,NaN,2.501493,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,NaN,NaN
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN

In [6]:
df.shape

(704, 21)

In [7]:
for column in list(df.columns):
  print(df[column].unique())

[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[0 1]
[0 1]
['26' '24' '27' '35' '40' '36' '17' '64' '29' '33' '18' '31' '30' '34'
 '38' '42' '43' '48' '37' '55' '50' '53' '20' '28' '21' '383' '47' '32'
 '44' '?' '19' '58' '45' '22' '39' '25' '23' '54' '60' '41' '46' '56' '61'
 '59' '52' '49' '51']
['f' 'm']
['White-European' 'Latino' '?' 'Others' 'Black' 'Asian'
 "'Middle Eastern '" 'Pasifika' "'South Asian'" 'Hispanic' 'Turkish'
 'others']
['no' 'yes']
['no' 'yes']
["'United States'" 'Brazil' 'Spain' 'Egypt' "'New Zealand'" 'Bahamas'
 'Burundi' 'Austria' 'Argentina' 'Jordan' 'Ireland'
 "'United Arab Emirates'" 'Afghanistan' 'Lebanon' "'United Kingdom'"
 "'South Africa'" 'Italy' 'Pakistan' 'Bangladesh' 'Chile' 'France' 'China'
 'Australia' 'Canada' "'Saudi Arabia'" 'Netherlands' 'Romania' 'Sweden'
 'Tonga' 'Oman' 'India' 'Philippines' "'Sri Lanka'" "'Sierra Leone'"
 'Ethiopia' "'Viet Nam'" 'Iran' "'Costa Rica'" 'Germany' 'Mexico' 'Russia'
 'Armenia' 'Iceland' 'Nicaragua' "'Hong Kong'" 'Japan' 'Ukraine'
 'Kazakhstan' 'AmericanSamoa' 'Uruguay' 'Serbia' 'Portugal' 'Malaysia'
 'Ecuador' 'Niger' 'Belgium' 'Bolivia' 'Aruba' 'Finland' 'Turkey' 'Nepal'
 'Indonesia' 'Angola' 'Azerbaijan' 'Iraq' "'Czech Republic'" 'Cyprus']
['no' 'yes']
[ 6  5  8  2  9 10  4  3  0  1  7]
["'18 and more'"]
['Self' 'Parent' '?' "'Health care professional'" 'Relative' 'Others']
['NO' 'YES']

In [8]:
df["used_app_before"].value_counts()

used_app_before
no     692
yes     12
Name: count, dtype: int64

In [9]:
df.age.replace("?",0,inplace=True)
df["age"] = df["age"].astype(int)
med_val=df.age.median()
df.age.replace("?",med_val,inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3569938229.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.age.replace("?",0,inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3569938229.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.age.replace("?",med_val,inplace=True)

In [10]:
df["age"].unique()

array([ 26,  24,  27,  35,  40,  36,  17,  64,  29,  33,  18,  31,  30,
        34,  38,  42,  43,  48,  37,  55,  50,  53,  20,  28,  21, 383,
        47,  32,  44,   0,  19,  58,  45,  22,  39,  25,  23,  54,  60,
        41,  46,  56,  61,  59,  52,  49,  51])

In [11]:
df = df[df["age"] != 383]

In [12]:
df[(df['relation']=="Relative")&(df["austim"]=='yes')].shape[0]

6

In [13]:
df[(df['relation']=="Parent")&(df["austim"]=='yes')].shape[0]

13

In [14]:
df.relation.replace("?","Parent",inplace=True)

df.relation.value_counts()

C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3380867966.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.relation.replace("?","Parent",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3380867966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.relation.replace("?","Parent",inplace=True)

relation
Self                          521
Parent                        145
Relative                       28
Others                          5
'Health care professional'      4
Name: count, dtype: int64

In [15]:
df.drop("age_desc",axis=1,inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\1650079591.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("age_desc",axis=1,inplace=True)

In [16]:
df['relation'].value_counts()

relation
Self                          521
Parent                        145
Relative                       28
Others                          5
'Health care professional'      4
Name: count, dtype: int64

In [17]:
df["ethnicity"].value_counts()

ethnicity
White-European       233
Asian                123
?                     95
'Middle Eastern '     92
Black                 43
'South Asian'         36
Others                30
Latino                20
Hispanic              13
Pasifika              11
Turkish                6
others                 1
Name: count, dtype: int64

In [18]:
df.loc[df["ethnicity"] == "others", "ethnicity"] = "Others"

In [19]:
df["ethnicity"].replace("?","Others",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\1393076813.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["ethnicity"].replace("?","Others",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\1393076813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ethnicity"].replace("?","Others",inplace=True)

In [20]:
dummies_Ethnicity=pd.get_dummies(df["ethnicity"])

In [21]:
dummies_Ethnicity

,'Middle Eastern ','South Asian',Asian,Black,Hispanic,Latino,Others,Pasifika,Turkish,White-European
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
699,False,False,False,False,False,False,False,False,False,True
700,False,False,False,False,True,False,False,False,False,False
701,False,False,False,False,False,False,True,False,False,False
702,False,True,False,False,False,False,False,False,False,False
703,False,False,False,False,False,False,False,False,False,True

In [22]:
dummies_relation=pd.get_dummies(df["relation"])

In [23]:

df["austim"] = df["austim"].map({'yes': 1, 'no': 0})
df["jundice"] = df["jundice"].map({'yes': 1, 'no': 0})
df["used_app_before"] = df["used_app_before"].map({"yes": 1, "no": 0})
df["gender"] = df["gender"].map({'m': 1, 'f': 0})
df["Class/ASD"] = df["Class/ASD"].map({"YES": 1, "NO": 0})

C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3440836461.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["austim"] = df["austim"].map({'yes': 1, 'no': 0})
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3440836461.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["jundice"] = df["jundice"].map({'yes': 1, 'no': 0})
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3440836461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["used_app_before"] = df["used_app_before"].map({"yes": 1, "no": 0})
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3440836461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gender"] = df["gender"].map({'m': 1, 'f': 0})
C:\Users\Admin\AppData\Local\Temp\ipykernel_18612\3440836461.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Class/ASD"] = df["Class/ASD"].map({"YES": 1, "NO": 0})

In [24]:
df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,age,gender,ethnicity,jundice,austim,coun_of_res,used_app_before,result,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,26,0,White-European,0,0,'United States',0,6,Self,0
1,1,1,0,1,0,0,0,1,0,1,24,1,Latino,0,1,Brazil,0,5,Self,0
2,1,1,0,1,1,0,1,1,1,1,27,1,Latino,1,1,Spain,0,8,Parent,1
3,1,1,0,1,0,0,1,1,0,1,35,0,White-European,0,1,'United States',0,6,Self,0
4,1,0,0,0,0,0,0,1,0,0,40,0,Others,0,0,Egypt,0,2,Parent,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,25,0,White-European,0,0,Russia,0,7,Self,1
700,1,0,0,0,0,0,0,1,0,1,34,1,Hispanic,0,0,Mexico,0,3,Parent,0
701,1,0,1,1,1,0,1,1,0,1,24,0,Others,0,0,Russia,0,7,Parent,1
702,1,0,0,1,1,0,1,0,1,1,35,1,'South Asian',0,0,Pakistan,0,6,Self,0
703,1,0,1,1,1,0,1,1,1,1,26,0,White-European,0,0,Cyprus,0,8,Self,1

In [25]:
df_all = pd.concat([df, dummies_Ethnicity,dummies_relation], axis=1)

In [26]:
df_all

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,Latino,Others,Pasifika,Turkish,White-European,'Health care professional',Others,Parent,Relative,Self
0,1,1,1,1,0,0,1,1,0,0,...,False,False,False,False,True,False,False,False,False,True
1,1,1,0,1,0,0,0,1,0,1,...,True,False,False,False,False,False,False,False,False,True
2,1,1,0,1,1,0,1,1,1,1,...,True,False,False,False,False,False,False,True,False,False
3,1,1,0,1,0,0,1,1,0,1,...,False,False,False,False,True,False,False,False,False,True
4,1,0,0,0,0,0,0,1,0,0,...,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,False,False,False,False,True,False,False,False,False,True
700,1,0,0,0,0,0,0,1,0,1,...,False,False,False,False,False,False,False,True,False,False
701,1,0,1,1,1,0,1,1,0,1,...,False,True,False,False,False,False,False,True,False,False
702,1,0,0,1,1,0,1,0,1,1,...,False,False,False,False,False,False,False,False,False,True
703,1,0,1,1,1,0,1,1,1,1,...,False,False,False,False,True,False,False,False,False,True

In [27]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 703 entries, 0 to 703
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   A1                          703 non-null    int64
 1   A2                          703 non-null    int64
 2   A3                          703 non-null    int64
 3   A4                          703 non-null    int64
 4   A5                          703 non-null    int64
 5   A6                          703 non-null    int64
 6   A7                          703 non-null    int64
 7   A8                          703 non-null    int64
 8   A9                          703 non-null    int64
 9   A10                         703 non-null    int64
 10  age                         703 non-null    int64
 11  gender                      703 non-null    int64
 12  ethnicity                   703 non-null    object
 13  jundice                     703 non-null    int64
 14  austim                      703 non-null    int64
 15  coun_of_res                 703 non-null    object
 16  used_app_before             703 non-null    int64
 17  result                      703 non-null    int64
 18  relation                    703 non-null    object
 19  Class/ASD                   703 non-null    int64
 20  'Middle Eastern '           703 non-null    bool
 21  'South Asian'               703 non-null    bool
 22  Asian                       703 non-null    bool
 23  Black                       703 non-null    bool
 24  Hispanic                    703 non-null    bool
 25  Latino                      703 non-null    bool
 26  Others                      703 non-null    bool
 27  Pasifika                    703 non-null    bool
 28  Turkish                     703 non-null    bool
 29  White-European              703 non-null    bool
 30  'Health care professional'  703 non-null    bool
 31  Others                      703 non-null    bool
 32  Parent                      703 non-null    bool
 33  Relative                    703 non-null    bool
 34  Self                        703 non-null    bool
dtypes: bool(15), int64(17), object(3)
memory usage: 125.6+ KB

In [28]:
df_all.drop(["ethnicity","relation","coun_of_res"],axis=1,inplace=True)

In [29]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 703 entries, 0 to 703
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   A1                          703 non-null    int64
 1   A2                          703 non-null    int64
 2   A3                          703 non-null    int64
 3   A4                          703 non-null    int64
 4   A5                          703 non-null    int64
 5   A6                          703 non-null    int64
 6   A7                          703 non-null    int64
 7   A8                          703 non-null    int64
 8   A9                          703 non-null    int64
 9   A10                         703 non-null    int64
 10  age                         703 non-null    int64
 11  gender                      703 non-null    int64
 12  jundice                     703 non-null    int64
 13  austim                      703 non-null    int64
 14  used_app_before             703 non-null    int64
 15  result                      703 non-null    int64
 16  Class/ASD                   703 non-null    int64
 17  'Middle Eastern '           703 non-null    bool
 18  'South Asian'               703 non-null    bool
 19  Asian                       703 non-null    bool
 20  Black                       703 non-null    bool
 21  Hispanic                    703 non-null    bool
 22  Latino                      703 non-null    bool
 23  Others                      703 non-null    bool
 24  Pasifika                    703 non-null    bool
 25  Turkish                     703 non-null    bool
 26  White-European              703 non-null    bool
 27  'Health care professional'  703 non-null    bool
 28  Others                      703 non-null    bool
 29  Parent                      703 non-null    bool
 30  Relative                    703 non-null    bool
 31  Self                        703 non-null    bool
dtypes: bool(15), int64(17)
memory usage: 109.2 KB

In [30]:
df_all

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,Latino,Others,Pasifika,Turkish,White-European,'Health care professional',Others,Parent,Relative,Self
0,1,1,1,1,0,0,1,1,0,0,...,False,False,False,False,True,False,False,False,False,True
1,1,1,0,1,0,0,0,1,0,1,...,True,False,False,False,False,False,False,False,False,True
2,1,1,0,1,1,0,1,1,1,1,...,True,False,False,False,False,False,False,True,False,False
3,1,1,0,1,0,0,1,1,0,1,...,False,False,False,False,True,False,False,False,False,True
4,1,0,0,0,0,0,0,1,0,0,...,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,False,False,False,False,True,False,False,False,False,True
700,1,0,0,0,0,0,0,1,0,1,...,False,False,False,False,False,False,False,True,False,False
701,1,0,1,1,1,0,1,1,0,1,...,False,True,False,False,False,False,False,True,False,False
702,1,0,0,1,1,0,1,0,1,1,...,False,False,False,False,False,False,False,False,False,True
703,1,0,1,1,1,0,1,1,1,1,...,False,False,False,False,True,False,False,False,False,True

In [32]:
df_all.columns

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'age',
       'gender', 'jundice', 'austim', 'used_app_before', 'result', 'Class/ASD',
       ''Middle Eastern '', ''South Asian'', 'Asian', 'Black', 'Hispanic',
       'Latino', 'Others', 'Pasifika', 'Turkish', 'White-European',
       ''Health care professional'', 'Others', 'Parent', 'Relative', 'Self'],
      dtype='object')